Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.network "private_network", ip: "192.168.99.11"
  #config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", use_dhcp_assigned_default_route: true

  # 缺省同步目录/vagrant为copy模式，改为nfs双向同步模式
  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  config.vm.provision "shell", inline: <<-SHELL
    echo "provision - HOME=$HOME , user=$(id -nu):$(id -ng)"
    echo 
    /vagrant/script/provision.sh
  SHELL

end

